mqtt:
  host: "iotwx.ucar.edu"
  port: 1883
  msg_topic: sensors/#
  topics:
    - "#"
database_api:
  base_url: http://database_api:8000
web:
  host:  10.2.2.153
  port: 5000
map:
  host:  10.2.2.153
  port: 5001
  station_timeout: 60
metabase:
  admin_data:
    first_name: Isaac
    last_name: Oppong-Baah
    email: admin@admin.edu
    password: "@siparcs25"
  config:
    site_name: IoTwx MB
  database:
    name: iotwx_db
    engine: postgres
    details:
      host: ${MB_DB_HOST}
      port: ${MB_DB_PORT}
      dbname: ${ORCH_DB_NAME}
      user: ${MB_DB_USER}
      password: ${MB_DB_PASS}
      ssl: false
    is_full_sync: true
    is_on_demand: false
    cache_ttl: null
  base_url: http://metabase:3000/api # This should correspond to the service name
