mqtt:
  broker_ip: 10.219.130.204 
  broker_port: 1884
  msg_topic: "lora_messages"
  assignment_timeout: 60
thingsboard:
  broker_ip: "thingsboard"
  broker_port: 1883  
  api_url: "http://10.219.130.204:8080"
  username: "tenant@thingsboard.org"
  password: "tenant"  # Replace with your tenant admin password
  default_device_type: "GPS_Station"  # New: Define a type for your dynamic devices
  dashboard_name: "Dynamic Station Map Dashboard"  # New: Name for the dashboard
db:
  host: "postgres"
  port: 5432
  
  name: "thingsboard"
  user: "postgres"
  password: "postgres"