FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY dynamic_assignment_network.py .
COPY config.yml /app/config.yml
EXPOSE 1883
ENV CONFIG_PATH=/app/config/config.yml
CMD ["python", "dynamic_assignment_network.py"]