version: '3.8'
services:
  dynamic_assignment_network:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - CONFIG_FILE_PATH=/app/config.yml
      - FLASK_ENV=production