apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.config.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.app.group }}
data:
  config.yaml: |
    mqtt:
      host: iotwx.ucar.edu
      port: 1883
      msg_topic: sensors/#
      topics:
        - "#"
    database_api:
      base_url: http://database-api:8000
    map:
      host: localhost
      port: 5001
    redis:
      host: redis
      port: 6379
    station:
      active_station_timeout: 150
      batch_interval: 60
    model_service:
      base_url: http://model-service:5000
    metabase:
      admin_data:
        first_name: Isaac
        last_name: Oppong-Baah
        email: admin@admin.edu
        password: "@siparcs25"
      config:
        site_name: IoTwx MB
      database:
        name: iotwx_db
        engine: postgres
        details:
          host: ${MB_DB_HOST}
          port: ${MB_DB_PORT}
          dbname: ${ORCH_DB_NAME}
          user: ${MB_DB_USER}
          password: ${MB_DB_PASS}
          ssl: false
        is_full_sync: true
        is_on_demand: false
        cache_ttl: null
      base_url: http://metabase:3000/api
      orch_url: http://orch-mb:8001
    thingsboard:
      broker_ip: "thingsboard-ce"
      broker_port: 1883  
      api_url: "http://thingsboard-ce:8080"
      username: "tenant@thingsboard.org"
      password: "tenant"
      default_device_type: "GPS_Station"
      dashboard_name: "Dynamic Station Dashboard"
