# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.credit.volume.static_data.name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  resources:
    requests:
      storage: {{ .Values.credit.volume.static_data.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.credit.volume.checkpoint.name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  resources:
    requests:
      storage: {{ .Values.credit.volume.checkpoint.size }}