# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.credit.volume.static_data }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-kubepv
  resources:
    requests:
      storage: {{ .Values.credit.volume.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.credit.volume.checkpoint }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-kubepv
  resources:
    requests:
      storage: {{ .Values.credit.volume.size }}