apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.group }}-esos
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: iotwx-ro
    kind: SecretStore
  target:
    name: {{ .Values.app.group }}-esos
  data:
    - secretKey: MB_ADMIN_EMAIL
      remoteRef:
        key: iotwx/cirrus
        property: MB_ADMIN_EMAIL
    - secretKey: MB_ADMIN_PASS
      remoteRef:
        key: iotwx/cirrus
        property: MB_ADMIN_PASS