apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.group }}-esos
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: iotwx-ro
    kind: SecretStore
  target:
    name: {{ .Values.app.group }}-esos
  data:
    - secretKey: MB_ADMIN_EMAIL
      remoteRef:
        key: iotwx/cirrus
        property: MB_ADMIN_EMAIL
    - secretKey: MB_ADMIN_PASS
      remoteRef:
        key: iotwx/cirrus
        property: MB_ADMIN_PASS
    - secretKey: MB_DB_PASS
      remoteRef:
        key: iotwx/cirrus
        property: MB_DB_PASS
    - secretKey: ORCH_DB_PASS
      remoteRef:
        key: iotwx/cirrus
        property: ORCH_DB_PASS
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: iotwx/cirrus
        property: SMTP_PASSWORD
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: iotwx/cirrus
        property: SMTP_USERNAME
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: iotwx/cirrus
        property: PGADMIN_DEFAULT_EMAIL
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: iotwx/cirrus
        property: PGADMIN_DEFAULT_PASSWORD
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: iotwx/cirrus
        property: POSTGRES_PASSWORD
    - secretKey: TB_USERNAME
      remoteRef:
        key: iotwx/cirrus
        property: TB_USERNAME
    - secretKey: TB_PASSWORD
      remoteRef:
        key: iotwx/cirrus
        property: TB_PASSWORD