apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mosquitto.config.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.app.group }}
data:
  config.yaml: |
    listener 1883
    allow_anonymous true