apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mosquitto.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.app.group }}
    cirrus/lb: internal
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.mosquitto.name }}.k8s.ucar.edu"
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.mosquitto.container.port }}
  selector:
    app: {{ .Values.mosquitto.name }}