apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.ollama.volume.name}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.volume.size}}