apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.postgres.name }}
    group: {{ .Values.app.group }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.postgres.name }}
        image: {{ .Values.postgres.container.image }}
        imagePullPolicy: {{ .Values.app.imagePullPolicy }}
        resources:
          limits:
            memory: {{ .Values.postgres.container.memory }}
            cpu: {{ .Values.postgres.container.cpu }}
        ports:
        - containerPort: {{ .Values.postgres.container.port }}
        env:
        - name: POSTGRES_DB
          value: 5000
        - name: POSTGRES_PASSWORD
          value: 5000
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.volume.name }}
        