apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.volume.name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-kubepv
  resources:
    requests:
      storage: {{ .Values.redis.volume.size }}