# This workflow builds docker images and pushes them to a Container Repository
# This workflow is specific to the metabase directory and image
# Set the workflow name
name: Metabase Orchestration Image Build & Push

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the images/base-image/ path
on:
  workflow_dispatch: 
  push:
    paths:
      - cloud/services/metabase/**
    branches:
      - cirrus

permissions:
  contents: read

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  build-push-base-image:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: ubuntu-latest
    # Set the steps to take in order
    steps:
      # Step 1 is to checkout the github repo used to build the Container Image
      - name: Check out the repo
        uses: actions/checkout@v4
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: registry login
        uses: docker/login-action@v3
        with:
          registry: hub.k8s.ucar.edu
          username: ${{ secrets.HARBOR_LOGIN }}
          password: ${{ secrets.HARBOR_SECRET }}
      - name: Build image
        run: |
          docker buildx build --push -f cloud/services/metabase/Dockerfile -t hub.k8s.ucar.edu/mesonet/metabase:${{ steps.date.outputs.date }} cloud/services/metabase/.